/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ReposCreateTagProtectionRequest struct for ReposCreateTagProtectionRequest
type ReposCreateTagProtectionRequest struct {
	// An optional glob pattern to match against when enforcing tag protection.
	Pattern string `json:"pattern"`
}

// NewReposCreateTagProtectionRequest instantiates a new ReposCreateTagProtectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReposCreateTagProtectionRequest(pattern string) *ReposCreateTagProtectionRequest {
	this := ReposCreateTagProtectionRequest{}
	this.Pattern = pattern
	return &this
}

// NewReposCreateTagProtectionRequestWithDefaults instantiates a new ReposCreateTagProtectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReposCreateTagProtectionRequestWithDefaults() *ReposCreateTagProtectionRequest {
	this := ReposCreateTagProtectionRequest{}
	return &this
}

// GetPattern returns the Pattern field value
func (o *ReposCreateTagProtectionRequest) GetPattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pattern
}

// GetPatternOk returns a tuple with the Pattern field value
// and a boolean to check if the value has been set.
func (o *ReposCreateTagProtectionRequest) GetPatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pattern, true
}

// SetPattern sets field value
func (o *ReposCreateTagProtectionRequest) SetPattern(v string) {
	o.Pattern = v
}

func (o ReposCreateTagProtectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pattern"] = o.Pattern
	}
	return json.Marshal(toSerialize)
}

type NullableReposCreateTagProtectionRequest struct {
	value *ReposCreateTagProtectionRequest
	isSet bool
}

func (v NullableReposCreateTagProtectionRequest) Get() *ReposCreateTagProtectionRequest {
	return v.value
}

func (v *NullableReposCreateTagProtectionRequest) Set(val *ReposCreateTagProtectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReposCreateTagProtectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReposCreateTagProtectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposCreateTagProtectionRequest(val *ReposCreateTagProtectionRequest) *NullableReposCreateTagProtectionRequest {
	return &NullableReposCreateTagProtectionRequest{value: val, isSet: true}
}

func (v NullableReposCreateTagProtectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposCreateTagProtectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


