/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
	"time"
)

// EnvironmentApprovalsEnvironmentsInner struct for EnvironmentApprovalsEnvironmentsInner
type EnvironmentApprovalsEnvironmentsInner struct {
	// The id of the environment.
	Id *int32 `json:"id,omitempty"`
	NodeId *string `json:"node_id,omitempty"`
	// The name of the environment.
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	// The time that the environment was created, in ISO 8601 format.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The time that the environment was last updated, in ISO 8601 format.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewEnvironmentApprovalsEnvironmentsInner instantiates a new EnvironmentApprovalsEnvironmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentApprovalsEnvironmentsInner() *EnvironmentApprovalsEnvironmentsInner {
	this := EnvironmentApprovalsEnvironmentsInner{}
	return &this
}

// NewEnvironmentApprovalsEnvironmentsInnerWithDefaults instantiates a new EnvironmentApprovalsEnvironmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentApprovalsEnvironmentsInnerWithDefaults() *EnvironmentApprovalsEnvironmentsInner {
	this := EnvironmentApprovalsEnvironmentsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetId(v int32) {
	o.Id = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetNodeId() string {
	if o == nil || o.NodeId == nil {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetNodeIdOk() (*string, bool) {
	if o == nil || o.NodeId == nil {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasNodeId() bool {
	if o != nil && o.NodeId != nil {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetNodeId(v string) {
	o.NodeId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetUrl(v string) {
	o.Url = &v
}

// GetHtmlUrl returns the HtmlUrl field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetHtmlUrl() string {
	if o == nil || o.HtmlUrl == nil {
		var ret string
		return ret
	}
	return *o.HtmlUrl
}

// GetHtmlUrlOk returns a tuple with the HtmlUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetHtmlUrlOk() (*string, bool) {
	if o == nil || o.HtmlUrl == nil {
		return nil, false
	}
	return o.HtmlUrl, true
}

// HasHtmlUrl returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasHtmlUrl() bool {
	if o != nil && o.HtmlUrl != nil {
		return true
	}

	return false
}

// SetHtmlUrl gets a reference to the given string and assigns it to the HtmlUrl field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetHtmlUrl(v string) {
	o.HtmlUrl = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *EnvironmentApprovalsEnvironmentsInner) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *EnvironmentApprovalsEnvironmentsInner) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *EnvironmentApprovalsEnvironmentsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o EnvironmentApprovalsEnvironmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.NodeId != nil {
		toSerialize["node_id"] = o.NodeId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.HtmlUrl != nil {
		toSerialize["html_url"] = o.HtmlUrl
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentApprovalsEnvironmentsInner struct {
	value *EnvironmentApprovalsEnvironmentsInner
	isSet bool
}

func (v NullableEnvironmentApprovalsEnvironmentsInner) Get() *EnvironmentApprovalsEnvironmentsInner {
	return v.value
}

func (v *NullableEnvironmentApprovalsEnvironmentsInner) Set(val *EnvironmentApprovalsEnvironmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentApprovalsEnvironmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentApprovalsEnvironmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentApprovalsEnvironmentsInner(val *EnvironmentApprovalsEnvironmentsInner) *NullableEnvironmentApprovalsEnvironmentsInner {
	return &NullableEnvironmentApprovalsEnvironmentsInner{value: val, isSet: true}
}

func (v NullableEnvironmentApprovalsEnvironmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentApprovalsEnvironmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


