/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// CodespacesUserPublicKey The public key used for setting user Codespaces' Secrets.
type CodespacesUserPublicKey struct {
	// The identifier for the key.
	KeyId string `json:"key_id"`
	// The Base64 encoded public key.
	Key string `json:"key"`
}

// NewCodespacesUserPublicKey instantiates a new CodespacesUserPublicKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodespacesUserPublicKey(keyId string, key string) *CodespacesUserPublicKey {
	this := CodespacesUserPublicKey{}
	this.KeyId = keyId
	this.Key = key
	return &this
}

// NewCodespacesUserPublicKeyWithDefaults instantiates a new CodespacesUserPublicKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodespacesUserPublicKeyWithDefaults() *CodespacesUserPublicKey {
	this := CodespacesUserPublicKey{}
	return &this
}

// GetKeyId returns the KeyId field value
func (o *CodespacesUserPublicKey) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *CodespacesUserPublicKey) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *CodespacesUserPublicKey) SetKeyId(v string) {
	o.KeyId = v
}

// GetKey returns the Key field value
func (o *CodespacesUserPublicKey) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CodespacesUserPublicKey) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CodespacesUserPublicKey) SetKey(v string) {
	o.Key = v
}

func (o CodespacesUserPublicKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key_id"] = o.KeyId
	}
	if true {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullableCodespacesUserPublicKey struct {
	value *CodespacesUserPublicKey
	isSet bool
}

func (v NullableCodespacesUserPublicKey) Get() *CodespacesUserPublicKey {
	return v.value
}

func (v *NullableCodespacesUserPublicKey) Set(val *CodespacesUserPublicKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCodespacesUserPublicKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCodespacesUserPublicKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodespacesUserPublicKey(val *CodespacesUserPublicKey) *NullableCodespacesUserPublicKey {
	return &NullableCodespacesUserPublicKey{value: val, isSet: true}
}

func (v NullableCodespacesUserPublicKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodespacesUserPublicKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


