/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ReposUpdateRequestSecurityAndAnalysisSecretScanning Use the `status` property to enable or disable secret scanning for this repository. For more information, see \"[About secret scanning](/code-security/secret-security/about-secret-scanning).\"
type ReposUpdateRequestSecurityAndAnalysisSecretScanning struct {
	// Can be `enabled` or `disabled`.
	Status *string `json:"status,omitempty"`
}

// NewReposUpdateRequestSecurityAndAnalysisSecretScanning instantiates a new ReposUpdateRequestSecurityAndAnalysisSecretScanning object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReposUpdateRequestSecurityAndAnalysisSecretScanning() *ReposUpdateRequestSecurityAndAnalysisSecretScanning {
	this := ReposUpdateRequestSecurityAndAnalysisSecretScanning{}
	return &this
}

// NewReposUpdateRequestSecurityAndAnalysisSecretScanningWithDefaults instantiates a new ReposUpdateRequestSecurityAndAnalysisSecretScanning object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReposUpdateRequestSecurityAndAnalysisSecretScanningWithDefaults() *ReposUpdateRequestSecurityAndAnalysisSecretScanning {
	this := ReposUpdateRequestSecurityAndAnalysisSecretScanning{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReposUpdateRequestSecurityAndAnalysisSecretScanning) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateRequestSecurityAndAnalysisSecretScanning) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReposUpdateRequestSecurityAndAnalysisSecretScanning) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ReposUpdateRequestSecurityAndAnalysisSecretScanning) SetStatus(v string) {
	o.Status = &v
}

func (o ReposUpdateRequestSecurityAndAnalysisSecretScanning) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableReposUpdateRequestSecurityAndAnalysisSecretScanning struct {
	value *ReposUpdateRequestSecurityAndAnalysisSecretScanning
	isSet bool
}

func (v NullableReposUpdateRequestSecurityAndAnalysisSecretScanning) Get() *ReposUpdateRequestSecurityAndAnalysisSecretScanning {
	return v.value
}

func (v *NullableReposUpdateRequestSecurityAndAnalysisSecretScanning) Set(val *ReposUpdateRequestSecurityAndAnalysisSecretScanning) {
	v.value = val
	v.isSet = true
}

func (v NullableReposUpdateRequestSecurityAndAnalysisSecretScanning) IsSet() bool {
	return v.isSet
}

func (v *NullableReposUpdateRequestSecurityAndAnalysisSecretScanning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposUpdateRequestSecurityAndAnalysisSecretScanning(val *ReposUpdateRequestSecurityAndAnalysisSecretScanning) *NullableReposUpdateRequestSecurityAndAnalysisSecretScanning {
	return &NullableReposUpdateRequestSecurityAndAnalysisSecretScanning{value: val, isSet: true}
}

func (v NullableReposUpdateRequestSecurityAndAnalysisSecretScanning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposUpdateRequestSecurityAndAnalysisSecretScanning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


