/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// FileCommitCommitParentsInner struct for FileCommitCommitParentsInner
type FileCommitCommitParentsInner struct {
	Url *string `json:"url,omitempty"`
	HtmlUrl *string `json:"html_url,omitempty"`
	Sha *string `json:"sha,omitempty"`
}

// NewFileCommitCommitParentsInner instantiates a new FileCommitCommitParentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileCommitCommitParentsInner() *FileCommitCommitParentsInner {
	this := FileCommitCommitParentsInner{}
	return &this
}

// NewFileCommitCommitParentsInnerWithDefaults instantiates a new FileCommitCommitParentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileCommitCommitParentsInnerWithDefaults() *FileCommitCommitParentsInner {
	this := FileCommitCommitParentsInner{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FileCommitCommitParentsInner) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileCommitCommitParentsInner) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FileCommitCommitParentsInner) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FileCommitCommitParentsInner) SetUrl(v string) {
	o.Url = &v
}

// GetHtmlUrl returns the HtmlUrl field value if set, zero value otherwise.
func (o *FileCommitCommitParentsInner) GetHtmlUrl() string {
	if o == nil || o.HtmlUrl == nil {
		var ret string
		return ret
	}
	return *o.HtmlUrl
}

// GetHtmlUrlOk returns a tuple with the HtmlUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileCommitCommitParentsInner) GetHtmlUrlOk() (*string, bool) {
	if o == nil || o.HtmlUrl == nil {
		return nil, false
	}
	return o.HtmlUrl, true
}

// HasHtmlUrl returns a boolean if a field has been set.
func (o *FileCommitCommitParentsInner) HasHtmlUrl() bool {
	if o != nil && o.HtmlUrl != nil {
		return true
	}

	return false
}

// SetHtmlUrl gets a reference to the given string and assigns it to the HtmlUrl field.
func (o *FileCommitCommitParentsInner) SetHtmlUrl(v string) {
	o.HtmlUrl = &v
}

// GetSha returns the Sha field value if set, zero value otherwise.
func (o *FileCommitCommitParentsInner) GetSha() string {
	if o == nil || o.Sha == nil {
		var ret string
		return ret
	}
	return *o.Sha
}

// GetShaOk returns a tuple with the Sha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileCommitCommitParentsInner) GetShaOk() (*string, bool) {
	if o == nil || o.Sha == nil {
		return nil, false
	}
	return o.Sha, true
}

// HasSha returns a boolean if a field has been set.
func (o *FileCommitCommitParentsInner) HasSha() bool {
	if o != nil && o.Sha != nil {
		return true
	}

	return false
}

// SetSha gets a reference to the given string and assigns it to the Sha field.
func (o *FileCommitCommitParentsInner) SetSha(v string) {
	o.Sha = &v
}

func (o FileCommitCommitParentsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.HtmlUrl != nil {
		toSerialize["html_url"] = o.HtmlUrl
	}
	if o.Sha != nil {
		toSerialize["sha"] = o.Sha
	}
	return json.Marshal(toSerialize)
}

type NullableFileCommitCommitParentsInner struct {
	value *FileCommitCommitParentsInner
	isSet bool
}

func (v NullableFileCommitCommitParentsInner) Get() *FileCommitCommitParentsInner {
	return v.value
}

func (v *NullableFileCommitCommitParentsInner) Set(val *FileCommitCommitParentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFileCommitCommitParentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFileCommitCommitParentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileCommitCommitParentsInner(val *FileCommitCommitParentsInner) *NullableFileCommitCommitParentsInner {
	return &NullableFileCommitCommitParentsInner{value: val, isSet: true}
}

func (v NullableFileCommitCommitParentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileCommitCommitParentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


