/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
	"fmt"
)

// WebhookConfigInsecureSsl - struct for WebhookConfigInsecureSsl
type WebhookConfigInsecureSsl struct {
	Float32 *float32
	String *string
}

// float32AsWebhookConfigInsecureSsl is a convenience function that returns float32 wrapped in WebhookConfigInsecureSsl
func Float32AsWebhookConfigInsecureSsl(v *float32) WebhookConfigInsecureSsl {
	return WebhookConfigInsecureSsl{
		Float32: v,
	}
}

// stringAsWebhookConfigInsecureSsl is a convenience function that returns string wrapped in WebhookConfigInsecureSsl
func StringAsWebhookConfigInsecureSsl(v *string) WebhookConfigInsecureSsl {
	return WebhookConfigInsecureSsl{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *WebhookConfigInsecureSsl) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			match++
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(WebhookConfigInsecureSsl)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(WebhookConfigInsecureSsl)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src WebhookConfigInsecureSsl) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *WebhookConfigInsecureSsl) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableWebhookConfigInsecureSsl struct {
	value *WebhookConfigInsecureSsl
	isSet bool
}

func (v NullableWebhookConfigInsecureSsl) Get() *WebhookConfigInsecureSsl {
	return v.value
}

func (v *NullableWebhookConfigInsecureSsl) Set(val *WebhookConfigInsecureSsl) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookConfigInsecureSsl) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookConfigInsecureSsl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookConfigInsecureSsl(val *WebhookConfigInsecureSsl) *NullableWebhookConfigInsecureSsl {
	return &NullableWebhookConfigInsecureSsl{value: val, isSet: true}
}

func (v NullableWebhookConfigInsecureSsl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookConfigInsecureSsl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


