/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
	"fmt"
)

// ReposAddTeamAccessRestrictionsRequest - struct for ReposAddTeamAccessRestrictionsRequest
type ReposAddTeamAccessRestrictionsRequest struct {
	ReposAddTeamAccessRestrictionsRequestOneOf *ReposAddTeamAccessRestrictionsRequestOneOf
	ArrayOfString *[]string
}

// ReposAddTeamAccessRestrictionsRequestOneOfAsReposAddTeamAccessRestrictionsRequest is a convenience function that returns ReposAddTeamAccessRestrictionsRequestOneOf wrapped in ReposAddTeamAccessRestrictionsRequest
func ReposAddTeamAccessRestrictionsRequestOneOfAsReposAddTeamAccessRestrictionsRequest(v *ReposAddTeamAccessRestrictionsRequestOneOf) ReposAddTeamAccessRestrictionsRequest {
	return ReposAddTeamAccessRestrictionsRequest{
		ReposAddTeamAccessRestrictionsRequestOneOf: v,
	}
}

// []stringAsReposAddTeamAccessRestrictionsRequest is a convenience function that returns []string wrapped in ReposAddTeamAccessRestrictionsRequest
func ArrayOfStringAsReposAddTeamAccessRestrictionsRequest(v *[]string) ReposAddTeamAccessRestrictionsRequest {
	return ReposAddTeamAccessRestrictionsRequest{
		ArrayOfString: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ReposAddTeamAccessRestrictionsRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ReposAddTeamAccessRestrictionsRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.ReposAddTeamAccessRestrictionsRequestOneOf)
	if err == nil {
		jsonReposAddTeamAccessRestrictionsRequestOneOf, _ := json.Marshal(dst.ReposAddTeamAccessRestrictionsRequestOneOf)
		if string(jsonReposAddTeamAccessRestrictionsRequestOneOf) == "{}" { // empty struct
			dst.ReposAddTeamAccessRestrictionsRequestOneOf = nil
		} else {
			match++
		}
	} else {
		dst.ReposAddTeamAccessRestrictionsRequestOneOf = nil
	}

	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfString = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ReposAddTeamAccessRestrictionsRequestOneOf = nil
		dst.ArrayOfString = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(ReposAddTeamAccessRestrictionsRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(ReposAddTeamAccessRestrictionsRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ReposAddTeamAccessRestrictionsRequest) MarshalJSON() ([]byte, error) {
	if src.ReposAddTeamAccessRestrictionsRequestOneOf != nil {
		return json.Marshal(&src.ReposAddTeamAccessRestrictionsRequestOneOf)
	}

	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ReposAddTeamAccessRestrictionsRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ReposAddTeamAccessRestrictionsRequestOneOf != nil {
		return obj.ReposAddTeamAccessRestrictionsRequestOneOf
	}

	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	// all schemas are nil
	return nil
}

type NullableReposAddTeamAccessRestrictionsRequest struct {
	value *ReposAddTeamAccessRestrictionsRequest
	isSet bool
}

func (v NullableReposAddTeamAccessRestrictionsRequest) Get() *ReposAddTeamAccessRestrictionsRequest {
	return v.value
}

func (v *NullableReposAddTeamAccessRestrictionsRequest) Set(val *ReposAddTeamAccessRestrictionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReposAddTeamAccessRestrictionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReposAddTeamAccessRestrictionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposAddTeamAccessRestrictionsRequest(val *ReposAddTeamAccessRestrictionsRequest) *NullableReposAddTeamAccessRestrictionsRequest {
	return &NullableReposAddTeamAccessRestrictionsRequest{value: val, isSet: true}
}

func (v NullableReposAddTeamAccessRestrictionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposAddTeamAccessRestrictionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


