/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories.
type ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions struct {
	// The list of user `login`s with dismissal access
	Users []string `json:"users,omitempty"`
	// The list of team `slug`s with dismissal access
	Teams []string `json:"teams,omitempty"`
	// The list of app `slug`s with dismissal access
	Apps []string `json:"apps,omitempty"`
}

// NewReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions instantiates a new ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions() *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions {
	this := ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions{}
	return &this
}

// NewReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictionsWithDefaults instantiates a new ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictionsWithDefaults() *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions {
	this := ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) GetUsers() []string {
	if o == nil || o.Users == nil {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) GetUsersOk() ([]string, bool) {
	if o == nil || o.Users == nil {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) HasUsers() bool {
	if o != nil && o.Users != nil {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) SetUsers(v []string) {
	o.Users = v
}

// GetTeams returns the Teams field value if set, zero value otherwise.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) GetTeams() []string {
	if o == nil || o.Teams == nil {
		var ret []string
		return ret
	}
	return o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) GetTeamsOk() ([]string, bool) {
	if o == nil || o.Teams == nil {
		return nil, false
	}
	return o.Teams, true
}

// HasTeams returns a boolean if a field has been set.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) HasTeams() bool {
	if o != nil && o.Teams != nil {
		return true
	}

	return false
}

// SetTeams gets a reference to the given []string and assigns it to the Teams field.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) SetTeams(v []string) {
	o.Teams = v
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) GetApps() []string {
	if o == nil || o.Apps == nil {
		var ret []string
		return ret
	}
	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) GetAppsOk() ([]string, bool) {
	if o == nil || o.Apps == nil {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) HasApps() bool {
	if o != nil && o.Apps != nil {
		return true
	}

	return false
}

// SetApps gets a reference to the given []string and assigns it to the Apps field.
func (o *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) SetApps(v []string) {
	o.Apps = v
}

func (o ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Users != nil {
		toSerialize["users"] = o.Users
	}
	if o.Teams != nil {
		toSerialize["teams"] = o.Teams
	}
	if o.Apps != nil {
		toSerialize["apps"] = o.Apps
	}
	return json.Marshal(toSerialize)
}

type NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions struct {
	value *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions
	isSet bool
}

func (v NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) Get() *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions {
	return v.value
}

func (v *NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) Set(val *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) {
	v.value = val
	v.isSet = true
}

func (v NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) IsSet() bool {
	return v.isSet
}

func (v *NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions(val *ReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) *NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions {
	return &NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions{value: val, isSet: true}
}

func (v NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposUpdateBranchProtectionRequestRequiredPullRequestReviewsDismissalRestrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


