/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
	"fmt"
)

// ReposSetAppAccessRestrictionsRequest - struct for ReposSetAppAccessRestrictionsRequest
type ReposSetAppAccessRestrictionsRequest struct {
	ReposSetAppAccessRestrictionsRequestOneOf *ReposSetAppAccessRestrictionsRequestOneOf
	ArrayOfString *[]string
}

// ReposSetAppAccessRestrictionsRequestOneOfAsReposSetAppAccessRestrictionsRequest is a convenience function that returns ReposSetAppAccessRestrictionsRequestOneOf wrapped in ReposSetAppAccessRestrictionsRequest
func ReposSetAppAccessRestrictionsRequestOneOfAsReposSetAppAccessRestrictionsRequest(v *ReposSetAppAccessRestrictionsRequestOneOf) ReposSetAppAccessRestrictionsRequest {
	return ReposSetAppAccessRestrictionsRequest{
		ReposSetAppAccessRestrictionsRequestOneOf: v,
	}
}

// []stringAsReposSetAppAccessRestrictionsRequest is a convenience function that returns []string wrapped in ReposSetAppAccessRestrictionsRequest
func ArrayOfStringAsReposSetAppAccessRestrictionsRequest(v *[]string) ReposSetAppAccessRestrictionsRequest {
	return ReposSetAppAccessRestrictionsRequest{
		ArrayOfString: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ReposSetAppAccessRestrictionsRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ReposSetAppAccessRestrictionsRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.ReposSetAppAccessRestrictionsRequestOneOf)
	if err == nil {
		jsonReposSetAppAccessRestrictionsRequestOneOf, _ := json.Marshal(dst.ReposSetAppAccessRestrictionsRequestOneOf)
		if string(jsonReposSetAppAccessRestrictionsRequestOneOf) == "{}" { // empty struct
			dst.ReposSetAppAccessRestrictionsRequestOneOf = nil
		} else {
			match++
		}
	} else {
		dst.ReposSetAppAccessRestrictionsRequestOneOf = nil
	}

	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfString = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ReposSetAppAccessRestrictionsRequestOneOf = nil
		dst.ArrayOfString = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(ReposSetAppAccessRestrictionsRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(ReposSetAppAccessRestrictionsRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ReposSetAppAccessRestrictionsRequest) MarshalJSON() ([]byte, error) {
	if src.ReposSetAppAccessRestrictionsRequestOneOf != nil {
		return json.Marshal(&src.ReposSetAppAccessRestrictionsRequestOneOf)
	}

	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ReposSetAppAccessRestrictionsRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ReposSetAppAccessRestrictionsRequestOneOf != nil {
		return obj.ReposSetAppAccessRestrictionsRequestOneOf
	}

	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	// all schemas are nil
	return nil
}

type NullableReposSetAppAccessRestrictionsRequest struct {
	value *ReposSetAppAccessRestrictionsRequest
	isSet bool
}

func (v NullableReposSetAppAccessRestrictionsRequest) Get() *ReposSetAppAccessRestrictionsRequest {
	return v.value
}

func (v *NullableReposSetAppAccessRestrictionsRequest) Set(val *ReposSetAppAccessRestrictionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReposSetAppAccessRestrictionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReposSetAppAccessRestrictionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposSetAppAccessRestrictionsRequest(val *ReposSetAppAccessRestrictionsRequest) *NullableReposSetAppAccessRestrictionsRequest {
	return &NullableReposSetAppAccessRestrictionsRequest{value: val, isSet: true}
}

func (v NullableReposSetAppAccessRestrictionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposSetAppAccessRestrictionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


