/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ReposUpdateReleaseRequest struct for ReposUpdateReleaseRequest
type ReposUpdateReleaseRequest struct {
	// The name of the tag.
	TagName *string `json:"tag_name,omitempty"`
	// Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch (usually `master`).
	TargetCommitish *string `json:"target_commitish,omitempty"`
	// The name of the release.
	Name *string `json:"name,omitempty"`
	// Text describing the contents of the tag.
	Body *string `json:"body,omitempty"`
	// `true` makes the release a draft, and `false` publishes the release.
	Draft *bool `json:"draft,omitempty"`
	// `true` to identify the release as a prerelease, `false` to identify the release as a full release.
	Prerelease *bool `json:"prerelease,omitempty"`
	// If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. If there is already a discussion linked to the release, this parameter is ignored. For more information, see \"[Managing categories for discussions in your repository](https://docs.github.com/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository).\"
	DiscussionCategoryName *string `json:"discussion_category_name,omitempty"`
}

// NewReposUpdateReleaseRequest instantiates a new ReposUpdateReleaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReposUpdateReleaseRequest() *ReposUpdateReleaseRequest {
	this := ReposUpdateReleaseRequest{}
	return &this
}

// NewReposUpdateReleaseRequestWithDefaults instantiates a new ReposUpdateReleaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReposUpdateReleaseRequestWithDefaults() *ReposUpdateReleaseRequest {
	this := ReposUpdateReleaseRequest{}
	return &this
}

// GetTagName returns the TagName field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetTagName() string {
	if o == nil || o.TagName == nil {
		var ret string
		return ret
	}
	return *o.TagName
}

// GetTagNameOk returns a tuple with the TagName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetTagNameOk() (*string, bool) {
	if o == nil || o.TagName == nil {
		return nil, false
	}
	return o.TagName, true
}

// HasTagName returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasTagName() bool {
	if o != nil && o.TagName != nil {
		return true
	}

	return false
}

// SetTagName gets a reference to the given string and assigns it to the TagName field.
func (o *ReposUpdateReleaseRequest) SetTagName(v string) {
	o.TagName = &v
}

// GetTargetCommitish returns the TargetCommitish field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetTargetCommitish() string {
	if o == nil || o.TargetCommitish == nil {
		var ret string
		return ret
	}
	return *o.TargetCommitish
}

// GetTargetCommitishOk returns a tuple with the TargetCommitish field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetTargetCommitishOk() (*string, bool) {
	if o == nil || o.TargetCommitish == nil {
		return nil, false
	}
	return o.TargetCommitish, true
}

// HasTargetCommitish returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasTargetCommitish() bool {
	if o != nil && o.TargetCommitish != nil {
		return true
	}

	return false
}

// SetTargetCommitish gets a reference to the given string and assigns it to the TargetCommitish field.
func (o *ReposUpdateReleaseRequest) SetTargetCommitish(v string) {
	o.TargetCommitish = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReposUpdateReleaseRequest) SetName(v string) {
	o.Name = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetBody() string {
	if o == nil || o.Body == nil {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetBodyOk() (*string, bool) {
	if o == nil || o.Body == nil {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasBody() bool {
	if o != nil && o.Body != nil {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *ReposUpdateReleaseRequest) SetBody(v string) {
	o.Body = &v
}

// GetDraft returns the Draft field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetDraft() bool {
	if o == nil || o.Draft == nil {
		var ret bool
		return ret
	}
	return *o.Draft
}

// GetDraftOk returns a tuple with the Draft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetDraftOk() (*bool, bool) {
	if o == nil || o.Draft == nil {
		return nil, false
	}
	return o.Draft, true
}

// HasDraft returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasDraft() bool {
	if o != nil && o.Draft != nil {
		return true
	}

	return false
}

// SetDraft gets a reference to the given bool and assigns it to the Draft field.
func (o *ReposUpdateReleaseRequest) SetDraft(v bool) {
	o.Draft = &v
}

// GetPrerelease returns the Prerelease field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetPrerelease() bool {
	if o == nil || o.Prerelease == nil {
		var ret bool
		return ret
	}
	return *o.Prerelease
}

// GetPrereleaseOk returns a tuple with the Prerelease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetPrereleaseOk() (*bool, bool) {
	if o == nil || o.Prerelease == nil {
		return nil, false
	}
	return o.Prerelease, true
}

// HasPrerelease returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasPrerelease() bool {
	if o != nil && o.Prerelease != nil {
		return true
	}

	return false
}

// SetPrerelease gets a reference to the given bool and assigns it to the Prerelease field.
func (o *ReposUpdateReleaseRequest) SetPrerelease(v bool) {
	o.Prerelease = &v
}

// GetDiscussionCategoryName returns the DiscussionCategoryName field value if set, zero value otherwise.
func (o *ReposUpdateReleaseRequest) GetDiscussionCategoryName() string {
	if o == nil || o.DiscussionCategoryName == nil {
		var ret string
		return ret
	}
	return *o.DiscussionCategoryName
}

// GetDiscussionCategoryNameOk returns a tuple with the DiscussionCategoryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposUpdateReleaseRequest) GetDiscussionCategoryNameOk() (*string, bool) {
	if o == nil || o.DiscussionCategoryName == nil {
		return nil, false
	}
	return o.DiscussionCategoryName, true
}

// HasDiscussionCategoryName returns a boolean if a field has been set.
func (o *ReposUpdateReleaseRequest) HasDiscussionCategoryName() bool {
	if o != nil && o.DiscussionCategoryName != nil {
		return true
	}

	return false
}

// SetDiscussionCategoryName gets a reference to the given string and assigns it to the DiscussionCategoryName field.
func (o *ReposUpdateReleaseRequest) SetDiscussionCategoryName(v string) {
	o.DiscussionCategoryName = &v
}

func (o ReposUpdateReleaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TagName != nil {
		toSerialize["tag_name"] = o.TagName
	}
	if o.TargetCommitish != nil {
		toSerialize["target_commitish"] = o.TargetCommitish
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	if o.Draft != nil {
		toSerialize["draft"] = o.Draft
	}
	if o.Prerelease != nil {
		toSerialize["prerelease"] = o.Prerelease
	}
	if o.DiscussionCategoryName != nil {
		toSerialize["discussion_category_name"] = o.DiscussionCategoryName
	}
	return json.Marshal(toSerialize)
}

type NullableReposUpdateReleaseRequest struct {
	value *ReposUpdateReleaseRequest
	isSet bool
}

func (v NullableReposUpdateReleaseRequest) Get() *ReposUpdateReleaseRequest {
	return v.value
}

func (v *NullableReposUpdateReleaseRequest) Set(val *ReposUpdateReleaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReposUpdateReleaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReposUpdateReleaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposUpdateReleaseRequest(val *ReposUpdateReleaseRequest) *NullableReposUpdateReleaseRequest {
	return &NullableReposUpdateReleaseRequest{value: val, isSet: true}
}

func (v NullableReposUpdateReleaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposUpdateReleaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


