/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ActionsListRepoSecrets200Response struct for ActionsListRepoSecrets200Response
type ActionsListRepoSecrets200Response struct {
	TotalCount int32 `json:"total_count"`
	Secrets []ActionsSecret `json:"secrets"`
}

// NewActionsListRepoSecrets200Response instantiates a new ActionsListRepoSecrets200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionsListRepoSecrets200Response(totalCount int32, secrets []ActionsSecret) *ActionsListRepoSecrets200Response {
	this := ActionsListRepoSecrets200Response{}
	this.TotalCount = totalCount
	this.Secrets = secrets
	return &this
}

// NewActionsListRepoSecrets200ResponseWithDefaults instantiates a new ActionsListRepoSecrets200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionsListRepoSecrets200ResponseWithDefaults() *ActionsListRepoSecrets200Response {
	this := ActionsListRepoSecrets200Response{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *ActionsListRepoSecrets200Response) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ActionsListRepoSecrets200Response) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ActionsListRepoSecrets200Response) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetSecrets returns the Secrets field value
func (o *ActionsListRepoSecrets200Response) GetSecrets() []ActionsSecret {
	if o == nil {
		var ret []ActionsSecret
		return ret
	}

	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value
// and a boolean to check if the value has been set.
func (o *ActionsListRepoSecrets200Response) GetSecretsOk() ([]ActionsSecret, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secrets, true
}

// SetSecrets sets field value
func (o *ActionsListRepoSecrets200Response) SetSecrets(v []ActionsSecret) {
	o.Secrets = v
}

func (o ActionsListRepoSecrets200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["total_count"] = o.TotalCount
	}
	if true {
		toSerialize["secrets"] = o.Secrets
	}
	return json.Marshal(toSerialize)
}

type NullableActionsListRepoSecrets200Response struct {
	value *ActionsListRepoSecrets200Response
	isSet bool
}

func (v NullableActionsListRepoSecrets200Response) Get() *ActionsListRepoSecrets200Response {
	return v.value
}

func (v *NullableActionsListRepoSecrets200Response) Set(val *ActionsListRepoSecrets200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableActionsListRepoSecrets200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableActionsListRepoSecrets200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionsListRepoSecrets200Response(val *ActionsListRepoSecrets200Response) *NullableActionsListRepoSecrets200Response {
	return &NullableActionsListRepoSecrets200Response{value: val, isSet: true}
}

func (v NullableActionsListRepoSecrets200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionsListRepoSecrets200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


