/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ActionsListSelfHostedRunnersForOrg200Response struct for ActionsListSelfHostedRunnersForOrg200Response
type ActionsListSelfHostedRunnersForOrg200Response struct {
	TotalCount int32 `json:"total_count"`
	Runners []Runner `json:"runners"`
}

// NewActionsListSelfHostedRunnersForOrg200Response instantiates a new ActionsListSelfHostedRunnersForOrg200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionsListSelfHostedRunnersForOrg200Response(totalCount int32, runners []Runner) *ActionsListSelfHostedRunnersForOrg200Response {
	this := ActionsListSelfHostedRunnersForOrg200Response{}
	this.TotalCount = totalCount
	this.Runners = runners
	return &this
}

// NewActionsListSelfHostedRunnersForOrg200ResponseWithDefaults instantiates a new ActionsListSelfHostedRunnersForOrg200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionsListSelfHostedRunnersForOrg200ResponseWithDefaults() *ActionsListSelfHostedRunnersForOrg200Response {
	this := ActionsListSelfHostedRunnersForOrg200Response{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *ActionsListSelfHostedRunnersForOrg200Response) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ActionsListSelfHostedRunnersForOrg200Response) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ActionsListSelfHostedRunnersForOrg200Response) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetRunners returns the Runners field value
func (o *ActionsListSelfHostedRunnersForOrg200Response) GetRunners() []Runner {
	if o == nil {
		var ret []Runner
		return ret
	}

	return o.Runners
}

// GetRunnersOk returns a tuple with the Runners field value
// and a boolean to check if the value has been set.
func (o *ActionsListSelfHostedRunnersForOrg200Response) GetRunnersOk() ([]Runner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Runners, true
}

// SetRunners sets field value
func (o *ActionsListSelfHostedRunnersForOrg200Response) SetRunners(v []Runner) {
	o.Runners = v
}

func (o ActionsListSelfHostedRunnersForOrg200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["total_count"] = o.TotalCount
	}
	if true {
		toSerialize["runners"] = o.Runners
	}
	return json.Marshal(toSerialize)
}

type NullableActionsListSelfHostedRunnersForOrg200Response struct {
	value *ActionsListSelfHostedRunnersForOrg200Response
	isSet bool
}

func (v NullableActionsListSelfHostedRunnersForOrg200Response) Get() *ActionsListSelfHostedRunnersForOrg200Response {
	return v.value
}

func (v *NullableActionsListSelfHostedRunnersForOrg200Response) Set(val *ActionsListSelfHostedRunnersForOrg200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableActionsListSelfHostedRunnersForOrg200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableActionsListSelfHostedRunnersForOrg200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionsListSelfHostedRunnersForOrg200Response(val *ActionsListSelfHostedRunnersForOrg200Response) *NullableActionsListSelfHostedRunnersForOrg200Response {
	return &NullableActionsListSelfHostedRunnersForOrg200Response{value: val, isSet: true}
}

func (v NullableActionsListSelfHostedRunnersForOrg200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionsListSelfHostedRunnersForOrg200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


