/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ReposCreateWebhookRequestConfig Key/value pairs to provide settings for this webhook. [These are defined below](https://docs.github.com/rest/reference/repos#create-hook-config-params).
type ReposCreateWebhookRequestConfig struct {
	// The URL to which the payloads will be delivered.
	Url *string `json:"url,omitempty"`
	// The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
	ContentType *string `json:"content_type,omitempty"`
	// If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value for [delivery signature headers](https://docs.github.com/webhooks/event-payloads/#delivery-headers).
	Secret *string `json:"secret,omitempty"`
	InsecureSsl *WebhookConfigInsecureSsl `json:"insecure_ssl,omitempty"`
	Token *string `json:"token,omitempty"`
	Digest *string `json:"digest,omitempty"`
}

// NewReposCreateWebhookRequestConfig instantiates a new ReposCreateWebhookRequestConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReposCreateWebhookRequestConfig() *ReposCreateWebhookRequestConfig {
	this := ReposCreateWebhookRequestConfig{}
	return &this
}

// NewReposCreateWebhookRequestConfigWithDefaults instantiates a new ReposCreateWebhookRequestConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReposCreateWebhookRequestConfigWithDefaults() *ReposCreateWebhookRequestConfig {
	this := ReposCreateWebhookRequestConfig{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ReposCreateWebhookRequestConfig) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposCreateWebhookRequestConfig) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ReposCreateWebhookRequestConfig) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ReposCreateWebhookRequestConfig) SetUrl(v string) {
	o.Url = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *ReposCreateWebhookRequestConfig) GetContentType() string {
	if o == nil || o.ContentType == nil {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposCreateWebhookRequestConfig) GetContentTypeOk() (*string, bool) {
	if o == nil || o.ContentType == nil {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *ReposCreateWebhookRequestConfig) HasContentType() bool {
	if o != nil && o.ContentType != nil {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *ReposCreateWebhookRequestConfig) SetContentType(v string) {
	o.ContentType = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *ReposCreateWebhookRequestConfig) GetSecret() string {
	if o == nil || o.Secret == nil {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposCreateWebhookRequestConfig) GetSecretOk() (*string, bool) {
	if o == nil || o.Secret == nil {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *ReposCreateWebhookRequestConfig) HasSecret() bool {
	if o != nil && o.Secret != nil {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *ReposCreateWebhookRequestConfig) SetSecret(v string) {
	o.Secret = &v
}

// GetInsecureSsl returns the InsecureSsl field value if set, zero value otherwise.
func (o *ReposCreateWebhookRequestConfig) GetInsecureSsl() WebhookConfigInsecureSsl {
	if o == nil || o.InsecureSsl == nil {
		var ret WebhookConfigInsecureSsl
		return ret
	}
	return *o.InsecureSsl
}

// GetInsecureSslOk returns a tuple with the InsecureSsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposCreateWebhookRequestConfig) GetInsecureSslOk() (*WebhookConfigInsecureSsl, bool) {
	if o == nil || o.InsecureSsl == nil {
		return nil, false
	}
	return o.InsecureSsl, true
}

// HasInsecureSsl returns a boolean if a field has been set.
func (o *ReposCreateWebhookRequestConfig) HasInsecureSsl() bool {
	if o != nil && o.InsecureSsl != nil {
		return true
	}

	return false
}

// SetInsecureSsl gets a reference to the given WebhookConfigInsecureSsl and assigns it to the InsecureSsl field.
func (o *ReposCreateWebhookRequestConfig) SetInsecureSsl(v WebhookConfigInsecureSsl) {
	o.InsecureSsl = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ReposCreateWebhookRequestConfig) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposCreateWebhookRequestConfig) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ReposCreateWebhookRequestConfig) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ReposCreateWebhookRequestConfig) SetToken(v string) {
	o.Token = &v
}

// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *ReposCreateWebhookRequestConfig) GetDigest() string {
	if o == nil || o.Digest == nil {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReposCreateWebhookRequestConfig) GetDigestOk() (*string, bool) {
	if o == nil || o.Digest == nil {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *ReposCreateWebhookRequestConfig) HasDigest() bool {
	if o != nil && o.Digest != nil {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *ReposCreateWebhookRequestConfig) SetDigest(v string) {
	o.Digest = &v
}

func (o ReposCreateWebhookRequestConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.ContentType != nil {
		toSerialize["content_type"] = o.ContentType
	}
	if o.Secret != nil {
		toSerialize["secret"] = o.Secret
	}
	if o.InsecureSsl != nil {
		toSerialize["insecure_ssl"] = o.InsecureSsl
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Digest != nil {
		toSerialize["digest"] = o.Digest
	}
	return json.Marshal(toSerialize)
}

type NullableReposCreateWebhookRequestConfig struct {
	value *ReposCreateWebhookRequestConfig
	isSet bool
}

func (v NullableReposCreateWebhookRequestConfig) Get() *ReposCreateWebhookRequestConfig {
	return v.value
}

func (v *NullableReposCreateWebhookRequestConfig) Set(val *ReposCreateWebhookRequestConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableReposCreateWebhookRequestConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableReposCreateWebhookRequestConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposCreateWebhookRequestConfig(val *ReposCreateWebhookRequestConfig) *NullableReposCreateWebhookRequestConfig {
	return &NullableReposCreateWebhookRequestConfig{value: val, isSet: true}
}

func (v NullableReposCreateWebhookRequestConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposCreateWebhookRequestConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


