/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ScimProvisionAndInviteUserRequestEmailsInner struct for ScimProvisionAndInviteUserRequestEmailsInner
type ScimProvisionAndInviteUserRequestEmailsInner struct {
	Value string `json:"value"`
	Primary *bool `json:"primary,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewScimProvisionAndInviteUserRequestEmailsInner instantiates a new ScimProvisionAndInviteUserRequestEmailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimProvisionAndInviteUserRequestEmailsInner(value string) *ScimProvisionAndInviteUserRequestEmailsInner {
	this := ScimProvisionAndInviteUserRequestEmailsInner{}
	this.Value = value
	return &this
}

// NewScimProvisionAndInviteUserRequestEmailsInnerWithDefaults instantiates a new ScimProvisionAndInviteUserRequestEmailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimProvisionAndInviteUserRequestEmailsInnerWithDefaults() *ScimProvisionAndInviteUserRequestEmailsInner {
	this := ScimProvisionAndInviteUserRequestEmailsInner{}
	return &this
}

// GetValue returns the Value field value
func (o *ScimProvisionAndInviteUserRequestEmailsInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ScimProvisionAndInviteUserRequestEmailsInner) SetValue(v string) {
	o.Value = v
}

// GetPrimary returns the Primary field value if set, zero value otherwise.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) GetPrimary() bool {
	if o == nil || o.Primary == nil {
		var ret bool
		return ret
	}
	return *o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) GetPrimaryOk() (*bool, bool) {
	if o == nil || o.Primary == nil {
		return nil, false
	}
	return o.Primary, true
}

// HasPrimary returns a boolean if a field has been set.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) HasPrimary() bool {
	if o != nil && o.Primary != nil {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given bool and assigns it to the Primary field.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) SetPrimary(v bool) {
	o.Primary = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ScimProvisionAndInviteUserRequestEmailsInner) SetType(v string) {
	o.Type = &v
}

func (o ScimProvisionAndInviteUserRequestEmailsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	if o.Primary != nil {
		toSerialize["primary"] = o.Primary
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableScimProvisionAndInviteUserRequestEmailsInner struct {
	value *ScimProvisionAndInviteUserRequestEmailsInner
	isSet bool
}

func (v NullableScimProvisionAndInviteUserRequestEmailsInner) Get() *ScimProvisionAndInviteUserRequestEmailsInner {
	return v.value
}

func (v *NullableScimProvisionAndInviteUserRequestEmailsInner) Set(val *ScimProvisionAndInviteUserRequestEmailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScimProvisionAndInviteUserRequestEmailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScimProvisionAndInviteUserRequestEmailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimProvisionAndInviteUserRequestEmailsInner(val *ScimProvisionAndInviteUserRequestEmailsInner) *NullableScimProvisionAndInviteUserRequestEmailsInner {
	return &NullableScimProvisionAndInviteUserRequestEmailsInner{value: val, isSet: true}
}

func (v NullableScimProvisionAndInviteUserRequestEmailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimProvisionAndInviteUserRequestEmailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


