/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions struct for ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions
type ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions struct {
	Url string `json:"url"`
	UsersUrl string `json:"users_url"`
	TeamsUrl string `json:"teams_url"`
	Users []SimpleUser `json:"users"`
	Teams []Team `json:"teams"`
	Apps []Integration `json:"apps,omitempty"`
}

// NewProtectedBranchRequiredPullRequestReviewsDismissalRestrictions instantiates a new ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectedBranchRequiredPullRequestReviewsDismissalRestrictions(url string, usersUrl string, teamsUrl string, users []SimpleUser, teams []Team) *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions {
	this := ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions{}
	this.Url = url
	this.UsersUrl = usersUrl
	this.TeamsUrl = teamsUrl
	this.Users = users
	this.Teams = teams
	return &this
}

// NewProtectedBranchRequiredPullRequestReviewsDismissalRestrictionsWithDefaults instantiates a new ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectedBranchRequiredPullRequestReviewsDismissalRestrictionsWithDefaults() *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions {
	this := ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions{}
	return &this
}

// GetUrl returns the Url field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) SetUrl(v string) {
	o.Url = v
}

// GetUsersUrl returns the UsersUrl field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetUsersUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UsersUrl
}

// GetUsersUrlOk returns a tuple with the UsersUrl field value
// and a boolean to check if the value has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetUsersUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsersUrl, true
}

// SetUsersUrl sets field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) SetUsersUrl(v string) {
	o.UsersUrl = v
}

// GetTeamsUrl returns the TeamsUrl field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetTeamsUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamsUrl
}

// GetTeamsUrlOk returns a tuple with the TeamsUrl field value
// and a boolean to check if the value has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetTeamsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamsUrl, true
}

// SetTeamsUrl sets field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) SetTeamsUrl(v string) {
	o.TeamsUrl = v
}

// GetUsers returns the Users field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetUsers() []SimpleUser {
	if o == nil {
		var ret []SimpleUser
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetUsersOk() ([]SimpleUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) SetUsers(v []SimpleUser) {
	o.Users = v
}

// GetTeams returns the Teams field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetTeams() []Team {
	if o == nil {
		var ret []Team
		return ret
	}

	return o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value
// and a boolean to check if the value has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetTeamsOk() ([]Team, bool) {
	if o == nil {
		return nil, false
	}
	return o.Teams, true
}

// SetTeams sets field value
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) SetTeams(v []Team) {
	o.Teams = v
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetApps() []Integration {
	if o == nil || o.Apps == nil {
		var ret []Integration
		return ret
	}
	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) GetAppsOk() ([]Integration, bool) {
	if o == nil || o.Apps == nil {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) HasApps() bool {
	if o != nil && o.Apps != nil {
		return true
	}

	return false
}

// SetApps gets a reference to the given []Integration and assigns it to the Apps field.
func (o *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) SetApps(v []Integration) {
	o.Apps = v
}

func (o ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["users_url"] = o.UsersUrl
	}
	if true {
		toSerialize["teams_url"] = o.TeamsUrl
	}
	if true {
		toSerialize["users"] = o.Users
	}
	if true {
		toSerialize["teams"] = o.Teams
	}
	if o.Apps != nil {
		toSerialize["apps"] = o.Apps
	}
	return json.Marshal(toSerialize)
}

type NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions struct {
	value *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions
	isSet bool
}

func (v NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) Get() *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions {
	return v.value
}

func (v *NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) Set(val *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions(val *ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) *NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions {
	return &NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions{value: val, isSet: true}
}

func (v NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectedBranchRequiredPullRequestReviewsDismissalRestrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


