/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// ProjectsMoveCardRequest struct for ProjectsMoveCardRequest
type ProjectsMoveCardRequest struct {
	// The position of the card in a column. Can be one of: `top`, `bottom`, or `after:<card_id>` to place after the specified card.
	Position string `json:"position"`
	// The unique identifier of the column the card should be moved to
	ColumnId *int32 `json:"column_id,omitempty"`
}

// NewProjectsMoveCardRequest instantiates a new ProjectsMoveCardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectsMoveCardRequest(position string) *ProjectsMoveCardRequest {
	this := ProjectsMoveCardRequest{}
	this.Position = position
	return &this
}

// NewProjectsMoveCardRequestWithDefaults instantiates a new ProjectsMoveCardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectsMoveCardRequestWithDefaults() *ProjectsMoveCardRequest {
	this := ProjectsMoveCardRequest{}
	return &this
}

// GetPosition returns the Position field value
func (o *ProjectsMoveCardRequest) GetPosition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *ProjectsMoveCardRequest) GetPositionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *ProjectsMoveCardRequest) SetPosition(v string) {
	o.Position = v
}

// GetColumnId returns the ColumnId field value if set, zero value otherwise.
func (o *ProjectsMoveCardRequest) GetColumnId() int32 {
	if o == nil || o.ColumnId == nil {
		var ret int32
		return ret
	}
	return *o.ColumnId
}

// GetColumnIdOk returns a tuple with the ColumnId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsMoveCardRequest) GetColumnIdOk() (*int32, bool) {
	if o == nil || o.ColumnId == nil {
		return nil, false
	}
	return o.ColumnId, true
}

// HasColumnId returns a boolean if a field has been set.
func (o *ProjectsMoveCardRequest) HasColumnId() bool {
	if o != nil && o.ColumnId != nil {
		return true
	}

	return false
}

// SetColumnId gets a reference to the given int32 and assigns it to the ColumnId field.
func (o *ProjectsMoveCardRequest) SetColumnId(v int32) {
	o.ColumnId = &v
}

func (o ProjectsMoveCardRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["position"] = o.Position
	}
	if o.ColumnId != nil {
		toSerialize["column_id"] = o.ColumnId
	}
	return json.Marshal(toSerialize)
}

type NullableProjectsMoveCardRequest struct {
	value *ProjectsMoveCardRequest
	isSet bool
}

func (v NullableProjectsMoveCardRequest) Get() *ProjectsMoveCardRequest {
	return v.value
}

func (v *NullableProjectsMoveCardRequest) Set(val *ProjectsMoveCardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectsMoveCardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectsMoveCardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectsMoveCardRequest(val *ProjectsMoveCardRequest) *NullableProjectsMoveCardRequest {
	return &NullableProjectsMoveCardRequest{value: val, isSet: true}
}

func (v NullableProjectsMoveCardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectsMoveCardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


