/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// PorterAuthor Porter Author
type PorterAuthor struct {
	Id int32 `json:"id"`
	RemoteId string `json:"remote_id"`
	RemoteName string `json:"remote_name"`
	Email string `json:"email"`
	Name string `json:"name"`
	Url string `json:"url"`
	ImportUrl string `json:"import_url"`
}

// NewPorterAuthor instantiates a new PorterAuthor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPorterAuthor(id int32, remoteId string, remoteName string, email string, name string, url string, importUrl string) *PorterAuthor {
	this := PorterAuthor{}
	this.Id = id
	this.RemoteId = remoteId
	this.RemoteName = remoteName
	this.Email = email
	this.Name = name
	this.Url = url
	this.ImportUrl = importUrl
	return &this
}

// NewPorterAuthorWithDefaults instantiates a new PorterAuthor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPorterAuthorWithDefaults() *PorterAuthor {
	this := PorterAuthor{}
	return &this
}

// GetId returns the Id field value
func (o *PorterAuthor) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PorterAuthor) SetId(v int32) {
	o.Id = v
}

// GetRemoteId returns the RemoteId field value
func (o *PorterAuthor) GetRemoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteId
}

// GetRemoteIdOk returns a tuple with the RemoteId field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetRemoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteId, true
}

// SetRemoteId sets field value
func (o *PorterAuthor) SetRemoteId(v string) {
	o.RemoteId = v
}

// GetRemoteName returns the RemoteName field value
func (o *PorterAuthor) GetRemoteName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteName
}

// GetRemoteNameOk returns a tuple with the RemoteName field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetRemoteNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteName, true
}

// SetRemoteName sets field value
func (o *PorterAuthor) SetRemoteName(v string) {
	o.RemoteName = v
}

// GetEmail returns the Email field value
func (o *PorterAuthor) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PorterAuthor) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *PorterAuthor) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PorterAuthor) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *PorterAuthor) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PorterAuthor) SetUrl(v string) {
	o.Url = v
}

// GetImportUrl returns the ImportUrl field value
func (o *PorterAuthor) GetImportUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImportUrl
}

// GetImportUrlOk returns a tuple with the ImportUrl field value
// and a boolean to check if the value has been set.
func (o *PorterAuthor) GetImportUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImportUrl, true
}

// SetImportUrl sets field value
func (o *PorterAuthor) SetImportUrl(v string) {
	o.ImportUrl = v
}

func (o PorterAuthor) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["remote_id"] = o.RemoteId
	}
	if true {
		toSerialize["remote_name"] = o.RemoteName
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["import_url"] = o.ImportUrl
	}
	return json.Marshal(toSerialize)
}

type NullablePorterAuthor struct {
	value *PorterAuthor
	isSet bool
}

func (v NullablePorterAuthor) Get() *PorterAuthor {
	return v.value
}

func (v *NullablePorterAuthor) Set(val *PorterAuthor) {
	v.value = val
	v.isSet = true
}

func (v NullablePorterAuthor) IsSet() bool {
	return v.isSet
}

func (v *NullablePorterAuthor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePorterAuthor(val *PorterAuthor) *NullablePorterAuthor {
	return &NullablePorterAuthor{value: val, isSet: true}
}

func (v NullablePorterAuthor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePorterAuthor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


