/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
	"time"
)

// TeamDiscussion A team discussion is a persistent record of a free-form conversation within a team.
type TeamDiscussion struct {
	Author NullableNullableSimpleUser `json:"author"`
	// The main text of the discussion.
	Body string `json:"body"`
	BodyHtml string `json:"body_html"`
	// The current version of the body content. If provided, this update operation will be rejected if the given version does not match the latest version on the server.
	BodyVersion string `json:"body_version"`
	CommentsCount int32 `json:"comments_count"`
	CommentsUrl string `json:"comments_url"`
	CreatedAt time.Time `json:"created_at"`
	LastEditedAt NullableTime `json:"last_edited_at"`
	HtmlUrl string `json:"html_url"`
	NodeId string `json:"node_id"`
	// The unique sequence number of a team discussion.
	Number int32 `json:"number"`
	// Whether or not this discussion should be pinned for easy retrieval.
	Pinned bool `json:"pinned"`
	// Whether or not this discussion should be restricted to team members and organization administrators.
	Private bool `json:"private"`
	TeamUrl string `json:"team_url"`
	// The title of the discussion.
	Title string `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	Url string `json:"url"`
	Reactions *ReactionRollup `json:"reactions,omitempty"`
}

// NewTeamDiscussion instantiates a new TeamDiscussion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamDiscussion(author NullableNullableSimpleUser, body string, bodyHtml string, bodyVersion string, commentsCount int32, commentsUrl string, createdAt time.Time, lastEditedAt NullableTime, htmlUrl string, nodeId string, number int32, pinned bool, private bool, teamUrl string, title string, updatedAt time.Time, url string) *TeamDiscussion {
	this := TeamDiscussion{}
	this.Author = author
	this.Body = body
	this.BodyHtml = bodyHtml
	this.BodyVersion = bodyVersion
	this.CommentsCount = commentsCount
	this.CommentsUrl = commentsUrl
	this.CreatedAt = createdAt
	this.LastEditedAt = lastEditedAt
	this.HtmlUrl = htmlUrl
	this.NodeId = nodeId
	this.Number = number
	this.Pinned = pinned
	this.Private = private
	this.TeamUrl = teamUrl
	this.Title = title
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewTeamDiscussionWithDefaults instantiates a new TeamDiscussion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamDiscussionWithDefaults() *TeamDiscussion {
	this := TeamDiscussion{}
	return &this
}

// GetAuthor returns the Author field value
// If the value is explicit nil, the zero value for NullableSimpleUser will be returned
func (o *TeamDiscussion) GetAuthor() NullableSimpleUser {
	if o == nil || o.Author.Get() == nil {
		var ret NullableSimpleUser
		return ret
	}

	return *o.Author.Get()
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TeamDiscussion) GetAuthorOk() (*NullableSimpleUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.Author.Get(), o.Author.IsSet()
}

// SetAuthor sets field value
func (o *TeamDiscussion) SetAuthor(v NullableSimpleUser) {
	o.Author.Set(&v)
}

// GetBody returns the Body field value
func (o *TeamDiscussion) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *TeamDiscussion) SetBody(v string) {
	o.Body = v
}

// GetBodyHtml returns the BodyHtml field value
func (o *TeamDiscussion) GetBodyHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BodyHtml
}

// GetBodyHtmlOk returns a tuple with the BodyHtml field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetBodyHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BodyHtml, true
}

// SetBodyHtml sets field value
func (o *TeamDiscussion) SetBodyHtml(v string) {
	o.BodyHtml = v
}

// GetBodyVersion returns the BodyVersion field value
func (o *TeamDiscussion) GetBodyVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BodyVersion
}

// GetBodyVersionOk returns a tuple with the BodyVersion field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetBodyVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BodyVersion, true
}

// SetBodyVersion sets field value
func (o *TeamDiscussion) SetBodyVersion(v string) {
	o.BodyVersion = v
}

// GetCommentsCount returns the CommentsCount field value
func (o *TeamDiscussion) GetCommentsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CommentsCount
}

// GetCommentsCountOk returns a tuple with the CommentsCount field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetCommentsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommentsCount, true
}

// SetCommentsCount sets field value
func (o *TeamDiscussion) SetCommentsCount(v int32) {
	o.CommentsCount = v
}

// GetCommentsUrl returns the CommentsUrl field value
func (o *TeamDiscussion) GetCommentsUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommentsUrl
}

// GetCommentsUrlOk returns a tuple with the CommentsUrl field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetCommentsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommentsUrl, true
}

// SetCommentsUrl sets field value
func (o *TeamDiscussion) SetCommentsUrl(v string) {
	o.CommentsUrl = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TeamDiscussion) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TeamDiscussion) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetLastEditedAt returns the LastEditedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TeamDiscussion) GetLastEditedAt() time.Time {
	if o == nil || o.LastEditedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastEditedAt.Get()
}

// GetLastEditedAtOk returns a tuple with the LastEditedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TeamDiscussion) GetLastEditedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastEditedAt.Get(), o.LastEditedAt.IsSet()
}

// SetLastEditedAt sets field value
func (o *TeamDiscussion) SetLastEditedAt(v time.Time) {
	o.LastEditedAt.Set(&v)
}

// GetHtmlUrl returns the HtmlUrl field value
func (o *TeamDiscussion) GetHtmlUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HtmlUrl
}

// GetHtmlUrlOk returns a tuple with the HtmlUrl field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetHtmlUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HtmlUrl, true
}

// SetHtmlUrl sets field value
func (o *TeamDiscussion) SetHtmlUrl(v string) {
	o.HtmlUrl = v
}

// GetNodeId returns the NodeId field value
func (o *TeamDiscussion) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *TeamDiscussion) SetNodeId(v string) {
	o.NodeId = v
}

// GetNumber returns the Number field value
func (o *TeamDiscussion) GetNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *TeamDiscussion) SetNumber(v int32) {
	o.Number = v
}

// GetPinned returns the Pinned field value
func (o *TeamDiscussion) GetPinned() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Pinned
}

// GetPinnedOk returns a tuple with the Pinned field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetPinnedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pinned, true
}

// SetPinned sets field value
func (o *TeamDiscussion) SetPinned(v bool) {
	o.Pinned = v
}

// GetPrivate returns the Private field value
func (o *TeamDiscussion) GetPrivate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Private
}

// GetPrivateOk returns a tuple with the Private field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetPrivateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Private, true
}

// SetPrivate sets field value
func (o *TeamDiscussion) SetPrivate(v bool) {
	o.Private = v
}

// GetTeamUrl returns the TeamUrl field value
func (o *TeamDiscussion) GetTeamUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamUrl
}

// GetTeamUrlOk returns a tuple with the TeamUrl field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetTeamUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamUrl, true
}

// SetTeamUrl sets field value
func (o *TeamDiscussion) SetTeamUrl(v string) {
	o.TeamUrl = v
}

// GetTitle returns the Title field value
func (o *TeamDiscussion) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TeamDiscussion) SetTitle(v string) {
	o.Title = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TeamDiscussion) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TeamDiscussion) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *TeamDiscussion) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *TeamDiscussion) SetUrl(v string) {
	o.Url = v
}

// GetReactions returns the Reactions field value if set, zero value otherwise.
func (o *TeamDiscussion) GetReactions() ReactionRollup {
	if o == nil || o.Reactions == nil {
		var ret ReactionRollup
		return ret
	}
	return *o.Reactions
}

// GetReactionsOk returns a tuple with the Reactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamDiscussion) GetReactionsOk() (*ReactionRollup, bool) {
	if o == nil || o.Reactions == nil {
		return nil, false
	}
	return o.Reactions, true
}

// HasReactions returns a boolean if a field has been set.
func (o *TeamDiscussion) HasReactions() bool {
	if o != nil && o.Reactions != nil {
		return true
	}

	return false
}

// SetReactions gets a reference to the given ReactionRollup and assigns it to the Reactions field.
func (o *TeamDiscussion) SetReactions(v ReactionRollup) {
	o.Reactions = &v
}

func (o TeamDiscussion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["author"] = o.Author.Get()
	}
	if true {
		toSerialize["body"] = o.Body
	}
	if true {
		toSerialize["body_html"] = o.BodyHtml
	}
	if true {
		toSerialize["body_version"] = o.BodyVersion
	}
	if true {
		toSerialize["comments_count"] = o.CommentsCount
	}
	if true {
		toSerialize["comments_url"] = o.CommentsUrl
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["last_edited_at"] = o.LastEditedAt.Get()
	}
	if true {
		toSerialize["html_url"] = o.HtmlUrl
	}
	if true {
		toSerialize["node_id"] = o.NodeId
	}
	if true {
		toSerialize["number"] = o.Number
	}
	if true {
		toSerialize["pinned"] = o.Pinned
	}
	if true {
		toSerialize["private"] = o.Private
	}
	if true {
		toSerialize["team_url"] = o.TeamUrl
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if o.Reactions != nil {
		toSerialize["reactions"] = o.Reactions
	}
	return json.Marshal(toSerialize)
}

type NullableTeamDiscussion struct {
	value *TeamDiscussion
	isSet bool
}

func (v NullableTeamDiscussion) Get() *TeamDiscussion {
	return v.value
}

func (v *NullableTeamDiscussion) Set(val *TeamDiscussion) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamDiscussion) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamDiscussion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamDiscussion(val *TeamDiscussion) *NullableTeamDiscussion {
	return &NullableTeamDiscussion{value: val, isSet: true}
}

func (v NullableTeamDiscussion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamDiscussion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


